import twilioRouter from "./twilio";
import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import companiesRouter from "./companies";
import clientsRouter from "./clients";
import leadsRouter from "./leads";
import dealsRouter from "./deals";
import meetingsRouter from "./meetings";
import tasksRouter from "./tasks";
import kpiRouter from "./kpi";
import bookingRouter from "./booking";
import payrollRouter from "./payroll";
import googleRouter from "./google";
import reportsRouter from "./reports";
import assistantRouter from "./assistant";
import compensationRouter from "./compensation";
import activityRouter from "./activity";
import goalsRouter from "./goals";
import notificationsRouter from "./notifications";
import automationsRouter from "./automations";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(companiesRouter);
router.use(clientsRouter);
router.use(leadsRouter);
router.use(dealsRouter);
router.use(meetingsRouter);
router.use(tasksRouter);
router.use(kpiRouter);
router.use(bookingRouter);
router.use(payrollRouter);
router.use(googleRouter);
router.use(reportsRouter);
router.use(assistantRouter);
router.use(compensationRouter);
router.use(activityRouter);
router.use(goalsRouter);
router.use(notificationsRouter);
router.use(automationsRouter);
router.use(twilioRouter);
export default router;
